// Copyright 2016 - 2026 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.25.0 or later.

package excelize

import "strconv"

// RecalcCell evaluates the formula in the given cell and persists the
// typed result into its cached <v>/<t> pair. The cell's <f> element,
// and its shared-formula master, ref span, and si index when present,
// are left untouched. Dependency resolution uses the same recursive
// evaluator as CalcCellValue, so a single call converges a chain of
// formulas that feed the target. Circular references are bounded by
// the workbook's MaxCalcIterations option.
//
// Returns ErrCellNoFormula when the target cell does not hold a
// formula. Any evaluation error from the calc engine is returned
// unwrapped so callers can match on it directly.
func (f *File) RecalcCell(sheet, cell string) error {
	ctx := &calcContext{
		entry:             sheet + "!" + cell,
		maxCalcIterations: f.options.MaxCalcIterations,
		iterations:        make(map[string]uint),
		iterationsCache:   make(map[string]formulaArg),
	}
	arg, err := f.calcCellValue(ctx, sheet, cell)
	if err != nil {
		return err
	}
	return f.setCellCachedValue(sheet, cell, arg)
}

// setCellCachedValue writes the cached value of a formula cell from a
// typed formulaArg without touching the cell's formula. The cell must
// already hold an <f> element or ErrCellNoFormula is returned. For
// shared-formula children the child's <v>/<t> are updated in isolation:
// the master's formula body and sibling children remain untouched.
func (f *File) setCellCachedValue(sheet, cell string, v formulaArg) error {
	f.mu.Lock()
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		f.mu.Unlock()
		return err
	}
	f.mu.Unlock()
	ws.mu.Lock()
	defer ws.mu.Unlock()
	c, _, _, err := ws.prepareCell(cell)
	if err != nil {
		return err
	}
	if c.F == nil {
		return ErrCellNoFormula
	}
	setCachedArg(c, v)
	return nil
}

// setCachedArg maps a typed formulaArg onto the xlsxC value/type pair
// exactly as Excel would store the cached result of a formula: numeric
// booleans as t="b", plain numbers as t="" (implicit numeric), strings
// as t="str" (the inline shape Excel uses for formula results), errors
// as t="e" with the error code in <v>. ArgMatrix and ArgList collapse
// to their first scalar element, matching formulaArg.Value. ArgEmpty
// and ArgUnknown both clear the cache. Any inline-string remnant from
// a prior cache is cleared so a string-to-number transition does not
// leak the old <is>.
func setCachedArg(c *xlsxC, v formulaArg) {
	c.IS = nil
	switch v.Type {
	case ArgNumber:
		if v.Boolean {
			c.T, c.V = setCellBool(v.Number != 0)
			return
		}
		c.T, c.V = "", strconv.FormatFloat(v.Number, 'f', -1, 64)
	case ArgString:
		c.T, c.V = "str", v.String
	case ArgError:
		c.T, c.V = "e", v.Error
	case ArgEmpty, ArgUnknown:
		c.T, c.V = "", ""
	case ArgMatrix:
		if head := v.ToList(); len(head) > 0 && head[0].Type != ArgMatrix {
			setCachedArg(c, head[0])
			return
		}
		c.T, c.V = "", ""
	case ArgList:
		if len(v.List) > 0 && v.List[0].Type != ArgMatrix && v.List[0].Type != ArgList {
			setCachedArg(c, v.List[0])
			return
		}
		c.T, c.V = "", ""
	}
}
