// Copyright 2016 - 2026 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.24.0 or later.

package excelize

import "fmt"

// RecalcOptions narrows the scope of Recalc.
type RecalcOptions struct {
	// Sheet limits recalc to a single worksheet when non-empty. An
	// empty value recalculates every formula in the workbook.
	Sheet string
	// Ref limits recalc to cells inside the given A1-style range
	// (e.g. `B2:D10`). Requires Sheet to be set.
	Ref string
}

// RecalcError aggregates the per-cell failures encountered by Recalc.
// Use errors.As to extract it from the value returned by Recalc. The
// individual cell errors are exposed via Unwrap so errors.Is /
// errors.As can descend into them.
type RecalcError struct {
	// Cells lists each formula that could not be evaluated, in the
	// order Recalc encountered them.
	Cells []RecalcCellError
}

// RecalcCellError describes a single cell whose formula could not be
// evaluated during Recalc. It implements the error interface itself
// so callers can use errors.As(err, &cellErr) to extract the address
// of a specific failure.
type RecalcCellError struct {
	Sheet string
	Cell  string
	Err   error
}

// Error formats this single cell failure as `sheet!cell: err`.
func (e RecalcCellError) Error() string {
	return fmt.Sprintf("%s!%s: %v", e.Sheet, e.Cell, e.Err)
}

// Unwrap returns the wrapped cause so errors.Is / errors.As descend
// into it.
func (e RecalcCellError) Unwrap() error { return e.Err }

// Error returns a human-readable summary listing the first failing cell
// and the total count. Use Cells (or errors.As on RecalcCellError) to
// walk the complete list.
func (e *RecalcError) Error() string {
	if len(e.Cells) == 0 {
		return "recalc: unknown error"
	}
	first := e.Cells[0]
	if len(e.Cells) == 1 {
		return fmt.Sprintf("recalc: %s", first.Error())
	}
	return fmt.Sprintf("recalc: %s (and %d more)", first.Error(), len(e.Cells)-1)
}

// Unwrap exposes the underlying per-cell errors for errors.Is /
// errors.As traversal.
func (e *RecalcError) Unwrap() []error {
	out := make([]error, len(e.Cells))
	for i := range e.Cells {
		out[i] = e.Cells[i]
	}
	return out
}

// Recalc evaluates every formula in scope and persists the result into
// the cell's cached `<v>`, preserving the `<f>` element and any
// shared-formula grouping. Typical use:
//
//	f, _ := excelize.OpenFile(path)
//	defer f.Close()
//	if err := f.Recalc(); err != nil { /* inspect *RecalcError */ }
//	_ = f.Save()
//
// Dependency resolution uses the same recursive evaluator as
// CalcCellValue, so chained formulas across sheets (including 3D
// references) converge in a single pass. Circular references are
// bounded by the workbook's MaxCalcIterations option, matching
// existing calc engine behaviour.
//
// When any formula cannot be evaluated, Recalc continues with the
// remaining cells and returns a *RecalcError listing every failure.
// Cells that did compute are still persisted.
func (f *File) Recalc(opts ...RecalcOptions) error {
	o := RecalcOptions{}
	if len(opts) > 0 {
		o = opts[0]
	}
	cells, err := f.collectRecalcCells(o)
	if err != nil {
		return err
	}
	f.clearCalcCache()

	var failures []RecalcCellError
	for _, target := range cells {
		ctx := &calcContext{
			entry:             target.sheet + "!" + target.cell,
			maxCalcIterations: f.options.MaxCalcIterations,
			iterations:        make(map[string]uint),
			iterationsCache:   make(map[string]formulaArg),
		}
		arg, calcErr := f.calcCellValue(ctx, target.sheet, target.cell)
		if calcErr != nil {
			failures = append(failures, RecalcCellError{
				Sheet: target.sheet,
				Cell:  target.cell,
				Err:   calcErr,
			})
			continue
		}
		if setErr := f.setCellCachedValue(target.sheet, target.cell, arg); setErr != nil {
			failures = append(failures, RecalcCellError{
				Sheet: target.sheet,
				Cell:  target.cell,
				Err:   setErr,
			})
		}
	}
	f.clearCalcCache()
	if len(failures) > 0 {
		return &RecalcError{Cells: failures}
	}
	return nil
}

// recalcTarget identifies a formula cell to recalculate.
type recalcTarget struct {
	sheet string
	cell  string
}

// collectRecalcCells walks the workbook and returns every formula cell
// inside the scope specified by RecalcOptions. The workbook is walked
// in sheet-list order; within a sheet, cells are visited by row then
// column. Ref is parsed relative to Sheet's origin.
func (f *File) collectRecalcCells(o RecalcOptions) ([]recalcTarget, error) {
	if o.Ref != "" && o.Sheet == "" {
		return nil, fmt.Errorf("recalc: Ref requires Sheet: %w", ErrParameterRequired)
	}
	var sheets []string
	if o.Sheet != "" {
		if idx, err := f.GetSheetIndex(o.Sheet); err != nil || idx < 0 {
			return nil, fmt.Errorf("recalc: sheet %q not found", o.Sheet)
		}
		sheets = []string{o.Sheet}
	} else {
		sheets = f.GetSheetList()
	}

	var (
		cells            []recalcTarget
		inScope          func(col, row int) bool
		colStart, colEnd int
		rowStart, rowEnd int
	)
	inScope = func(_, _ int) bool { return true }
	if o.Ref != "" {
		coords, err := rangeRefToCoordinates(o.Ref)
		if err != nil {
			return nil, fmt.Errorf("recalc: invalid Ref: %w", err)
		}
		_ = sortCoordinates(coords)
		colStart, rowStart, colEnd, rowEnd = coords[0], coords[1], coords[2], coords[3]
		inScope = func(col, row int) bool {
			return col >= colStart && col <= colEnd && row >= rowStart && row <= rowEnd
		}
	}

	for _, sn := range sheets {
		ws, err := f.workSheetReader(sn)
		if err != nil {
			return nil, err
		}
		for r := range ws.SheetData.Row {
			row := &ws.SheetData.Row[r]
			for i := range row.C {
				c := &row.C[i]
				if c.F == nil {
					continue
				}
				col, rowNum, cellErr := CellNameToCoordinates(c.R)
				if cellErr != nil {
					continue
				}
				if !inScope(col, rowNum) {
					continue
				}
				cells = append(cells, recalcTarget{sheet: sn, cell: c.R})
			}
		}
	}
	return cells, nil
}

// ensure RecalcError implements the error interface.
var _ error = (*RecalcError)(nil)
