// Copyright 2016 - 2026 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.25.0 or later.

package excelize

import (
	"bufio"
	"bytes"
	"encoding/xml"
	"io"
	"math"
	"os"
	"strconv"
	"strings"

	"github.com/tiendc/go-deepcopy"
)

// duplicateHelperFunc defines functions to duplicate helper.
var duplicateHelperFunc = [3]func(*File, *xlsxWorksheet, string, int, int) error{
	func(f *File, ws *xlsxWorksheet, sheet string, row, row2 int) error {
		return f.duplicateConditionalFormat(ws, sheet, row, row2)
	},
	func(f *File, ws *xlsxWorksheet, sheet string, row, row2 int) error {
		return f.duplicateDataValidations(ws, sheet, row, row2)
	},
	func(f *File, ws *xlsxWorksheet, sheet string, row, row2 int) error {
		return f.duplicateMergeCells(ws, sheet, row, row2)
	},
}

// GetRows return all the rows in a sheet by given worksheet name, returned as
// a two-dimensional array, where the value of the cell is converted to the
// string type. If the cell format can be applied to the value of the cell,
// the applied value will be used, otherwise the original value will be used.
// GetRows fetched the rows with value or formula cells, the continually blank
// cells in the tail of each row will be skipped, so the length of each row
// may be inconsistent.
//
// For example, get and traverse the value of all cells by rows on a worksheet
// named 'Sheet1':
//
//	rows, err := f.GetRows("Sheet1")
//	if err != nil {
//	    fmt.Println(err)
//	    return
//	}
//	for _, row := range rows {
//	    for _, colCell := range row {
//	        fmt.Print(colCell, "\t")
//	    }
//	    fmt.Println()
//	}
func (f *File) GetRows(sheet string, opts ...Options) ([][]string, error) {
	rows, err := f.Rows(sheet)
	if err != nil {
		return nil, err
	}
	results, cur, maxVal := make([][]string, 0, 64), 0, 0
	for rows.Next() {
		cur++
		row, err := rows.Columns(opts...)
		if err != nil {
			break
		}
		if len(row) > 0 {
			if emptyRows := cur - maxVal - 1; emptyRows > 0 {
				results = append(results, make([][]string, emptyRows)...)
			}
			results = append(results, row)
			maxVal = cur
		}
	}
	return results[:maxVal], rows.Close()
}

// Rows defines an iterator to a sheet.
type Rows struct {
	err                     error
	curRow, seekRow         int
	needClose, rawCellValue bool
	sheet                   string
	f                       *File
	tempFile                *os.File
	sst                     *xlsxSST
	decoder                 *xml.Decoder
	token                   xml.Token
	curRowOpts, seekRowOpts RowOpts
	// Fast path: reusable cell struct to avoid per-cell allocation
	cellBuf xlsxC
	// Learned column count for pre-allocation
	numCols int
}

// Next will return true if it finds the next row element.
func (rows *Rows) Next() bool {
	rows.seekRow++
	if rows.curRow >= rows.seekRow {
		rows.curRowOpts = rows.seekRowOpts
		return true
	}
	for {
		token, _ := rows.decoder.Token()
		if token == nil {
			return false
		}
		switch xmlElement := token.(type) {
		case xml.StartElement:
			if xmlElement.Name.Local == "row" {
				rows.curRow++
				if rowNum, _ := attrValToInt("r", xmlElement.Attr); rowNum != 0 {
					rows.curRow = rowNum
				}
				rows.token = token
				rows.curRowOpts = extractRowOpts(xmlElement.Attr)
				return true
			}
		case xml.EndElement:
			if xmlElement.Name.Local == "sheetData" {
				return false
			}
		}
	}
}

// GetRowOpts will return the RowOpts of the current row.
func (rows *Rows) GetRowOpts() RowOpts {
	return rows.curRowOpts
}

// Error will return the error when the error occurs.
func (rows *Rows) Error() error {
	return rows.err
}

// Close closes the open worksheet XML file in the system temporary
// directory.
func (rows *Rows) Close() error {
	tempFile := rows.tempFile
	rows.tempFile = nil
	if tempFile != nil {
		return tempFile.Close()
	}
	return nil
}

// Columns return the current row's column values. This fetches the worksheet
// data as a stream, returns each cell in a row as is, and will not skip empty
// rows in the tail of the worksheet.
func (rows *Rows) Columns(opts ...Options) ([]string, error) {
	if rows.curRow > rows.seekRow {
		return nil, nil
	}
	// Pre-allocate cells slice based on learned column count
	var rowIterator rowXMLIterator
	if rows.numCols > 0 {
		rowIterator.cells = make([]string, 0, rows.numCols)
	}
	var token xml.Token
	rows.rawCellValue = rows.f.getOptions(opts...).RawCellValue
	// Fast path: skip sharedStringsReader if FastReadMode already loaded SST
	if !rows.f.fastSSTLoaded {
		if rows.sst, rowIterator.err = rows.f.sharedStringsReader(); rowIterator.err != nil {
			return rowIterator.cells, rowIterator.err
		}
	}
	for {
		if rows.token != nil {
			token = rows.token
		} else if token, _ = rows.decoder.Token(); token == nil {
			break
		}
		switch xmlElement := token.(type) {
		case xml.StartElement:
			rowIterator.inElement = xmlElement.Name.Local
			if rowIterator.inElement == "row" {
				rowNum := 0
				if rowNum, rowIterator.err = attrValToInt("r", xmlElement.Attr); rowNum != 0 {
					rows.curRow = rowNum
				} else if rows.token == nil {
					rows.curRow++
				}
				rows.token = token
				rows.seekRowOpts = extractRowOpts(xmlElement.Attr)
				if rows.curRow > rows.seekRow {
					rows.token = nil
					// Learn column count for next row's pre-allocation
					if rows.numCols == 0 && len(rowIterator.cells) > 0 {
						rows.numCols = len(rowIterator.cells)
					}
					return rowIterator.cells, rowIterator.err
				}
			}
			if rows.rowXMLHandler(&rowIterator, &xmlElement, rows.rawCellValue); rowIterator.err != nil {
				rows.token = nil
				return rowIterator.cells, rowIterator.err
			}
			rows.token = nil
		case xml.EndElement:
			if xmlElement.Name.Local == "sheetData" {
				if rows.numCols == 0 && len(rowIterator.cells) > 0 {
					rows.numCols = len(rowIterator.cells)
				}
				return rowIterator.cells, rowIterator.err
			}
		}
	}
	if rows.numCols == 0 && len(rowIterator.cells) > 0 {
		rows.numCols = len(rowIterator.cells)
	}
	return rowIterator.cells, rowIterator.err
}

// colRefToIndex extracts the 1-based column index from a cell reference
// like "B5" → 2, "AA3" → 27. This is an inline optimized version that
// avoids the overhead of CellNameToCoordinates.
func colRefToIndex(cellRef string) int {
	col := 0
	for i := 0; i < len(cellRef); i++ {
		ch := cellRef[i]
		if ch >= 'A' && ch <= 'Z' {
			col = col*26 + int(ch-'A') + 1
		} else if ch >= 'a' && ch <= 'z' {
			col = col*26 + int(ch-'a') + 1
		} else {
			break // hit digit
		}
	}
	return col
}

// extractRowOpts extract row element attributes.
func extractRowOpts(attrs []xml.Attr) RowOpts {
	rowOpts := RowOpts{Height: defaultRowHeight}
	if styleID, err := attrValToInt("s", attrs); err == nil && styleID > 0 && styleID < MaxCellStyles {
		rowOpts.StyleID = styleID
	}
	if hidden, err := attrValToBool("hidden", attrs); err == nil {
		rowOpts.Hidden = hidden
	}
	if height, err := attrValToFloat("ht", attrs); err == nil {
		rowOpts.Height = height
	}
	return rowOpts
}

// appendSpace append blank characters to slice by given length and source slice.
func appendSpace(l int, s []string) []string {
	for i := 1; i < l; i++ {
		s = append(s, "")
	}
	return s
}

// rowXMLIterator defined runtime use field for the worksheet row SAX parser.
type rowXMLIterator struct {
	err              error
	inElement        string
	cellCol, cellRow int
	cells            []string
}

// rowXMLHandler parse the row XML element of the worksheet.
func (rows *Rows) rowXMLHandler(rowIterator *rowXMLIterator, xmlElement *xml.StartElement, raw bool) {
	if rowIterator.inElement == "c" {
		rowIterator.cellCol++
		// Reuse cell buffer in FastReadMode to avoid per-cell allocation
		cell := &rows.cellBuf
		cell.reset()
		_ = cell.cellXMLHandler(rows.decoder, xmlElement)
		if cell.R != "" {
			// Use fast inline column parser when FastReadMode is enabled
			if rows.f.fastSSTLoaded {
				rowIterator.cellCol = colRefToIndex(cell.R)
			} else if rowIterator.cellCol, _, rowIterator.err = CellNameToCoordinates(cell.R); rowIterator.err != nil {
				return
			}
		}
		blank := rowIterator.cellCol - len(rowIterator.cells)
		if val, _ := cell.getValueFrom(rows.f, rows.sst, raw); val != "" || cell.F != nil {
			rowIterator.cells = append(appendSpace(blank, rowIterator.cells), val)
		}
	}
}

// cellXMLAttrHandler parse the cell XML element attributes of the worksheet.
func (cell *xlsxC) cellXMLAttrHandler(start *xml.StartElement) error {
	for _, attr := range start.Attr {
		switch attr.Name.Local {
		case "r":
			cell.R = attr.Value
		case "s":
			val, err := strconv.ParseInt(attr.Value, 10, 64)
			if err != nil {
				return err
			}
			if math.MinInt <= val && val <= math.MaxInt {
				cell.S = int(val)
			}
		case "t":
			cell.T = attr.Value
		default:
		}
	}
	return nil
}

// readCharData reads the text content of a simple XML element (already past
// its StartElement) and consumes through the EndElement. This avoids
// xml.Decoder.DecodeElement's reflection overhead for simple string targets.
func readCharData(d *xml.Decoder) (string, error) {
	for {
		tok, err := d.Token()
		if err != nil {
			return "", err
		}
		switch t := tok.(type) {
		case xml.CharData:
			s := string(t)
			// consume end element
			if _, err = d.Token(); err != nil {
				return s, err
			}
			return s, nil
		case xml.EndElement:
			// empty element: <v></v> or self-closing
			return "", nil
		}
	}
}

// cellXMLHandler parse the cell XML element of the worksheet.
// The implementation avoids passing field addresses to DecodeElement for the
// common <v> path so that the caller's xlsxC stays on the stack.
func (cell *xlsxC) cellXMLHandler(decoder *xml.Decoder, start *xml.StartElement) error {
	cell.XMLName = start.Name
	err := cell.cellXMLAttrHandler(start)
	if err != nil {
		return err
	}
	for {
		tok, err := decoder.Token()
		if err != nil {
			return err
		}
		var se xml.StartElement
		switch el := tok.(type) {
		case xml.StartElement:
			se = el
			switch se.Name.Local {
			case "v":
				// Hand-parse: read CharData + EndElement directly,
				// avoiding DecodeElement's reflect machinery (saves
				// ~8M allocs per 100K×20 file).
				cell.V, err = readCharData(decoder)
			case "f":
				// Use a local so &f escapes instead of cell.
				var f xlsxF
				err = decoder.DecodeElement(&f, &se)
				cell.F = &f
			case "is":
				// Use a local so &is escapes instead of cell.
				var is xlsxSI
				err = decoder.DecodeElement(&is, &se)
				cell.IS = &is
			}
			if err != nil {
				return err
			}
		case xml.EndElement:
			if el == start.End() {
				return nil
			}
		}
	}
}

// Rows returns a rows iterator, used for streaming reading data for a
// worksheet with a large data. This function is concurrency safe. For
// example:
//
//	rows, err := f.Rows("Sheet1")
//	if err != nil {
//	    fmt.Println(err)
//	    return
//	}
//	for rows.Next() {
//	    row, err := rows.Columns()
//	    if err != nil {
//	        fmt.Println(err)
//	    }
//	    for _, colCell := range row {
//	        fmt.Print(colCell, "\t")
//	    }
//	    fmt.Println()
//	}
//	if err = rows.Close(); err != nil {
//	    fmt.Println(err)
//	}
func (f *File) Rows(sheet string) (*Rows, error) {
	if err := checkSheetName(sheet); err != nil {
		return nil, err
	}
	name, ok := f.getSheetXMLPath(sheet)
	if !ok {
		return nil, ErrSheetNotExist{sheet}
	}
	if worksheet, ok := f.Sheet.Load(name); ok && worksheet != nil {
		ws := worksheet.(*xlsxWorksheet)
		ws.mu.Lock()
		defer ws.mu.Unlock()
		// Flush data
		output, _ := xml.Marshal(ws)
		f.saveFileList(name, f.replaceNameSpaceBytes(name, output))
	}
	// In FastReadMode, preload shared strings to avoid per-cell disk I/O
	if f.options != nil && f.options.FastReadMode && !f.fastSSTLoaded {
		if err := f.preloadSharedStrings(); err != nil {
			return nil, err
		}
	}
	var err error
	rows := Rows{f: f, sheet: name}
	rows.needClose, rows.decoder, rows.tempFile, err = f.xmlDecoder(name)
	return &rows, err
}

// FastRows defines an ultra-fast row iterator optimized for maximum read
// performance. It bypasses the standard xml.Decoder and uses direct byte
// scanning for minimal allocations. This is typically 30-50% faster than
// the standard Rows iterator with FastReadMode.
//
// Limitations:
//   - Requires FastReadMode to be enabled when opening the file
//   - Only returns raw string values (no date/number formatting)
//   - Does not support formulas or inline strings
//   - The returned row slice is reused between calls - copy if you need to retain
type FastRows struct {
	f       *File
	reader  *bufio.Reader
	closer  io.Closer
	rowBuf  []string // reusable row buffer
	cellBuf []byte   // reusable buffer for cell value extraction
	numCols int      // learned column count
	curRow  int      // current row number
	eof     bool     // reached end of sheetData
}

// RowsFast returns an ultra-fast row iterator for streaming reads. This
// method requires FastReadMode to be enabled when opening the file.
// It provides significantly better performance than Rows() by using
// direct byte scanning instead of xml.Decoder.
//
// Example:
//
//	f, err := excelize.OpenFile("Book1.xlsx", excelize.Options{FastReadMode: true})
//	if err != nil {
//	    return err
//	}
//	defer f.Close()
//
//	rows, err := f.RowsFast("Sheet1")
//	if err != nil {
//	    return err
//	}
//	defer rows.Close()
//
//	for rows.Next() {
//	    row := rows.Row()
//	    // Process row - note: slice is reused, copy if needed
//	}
func (f *File) RowsFast(sheet string) (*FastRows, error) {
	if f.options == nil || !f.options.FastReadMode {
		return nil, ErrParameterInvalid
	}
	if err := checkSheetName(sheet); err != nil {
		return nil, err
	}
	name, ok := f.getSheetXMLPath(sheet)
	if !ok {
		return nil, ErrSheetNotExist{sheet}
	}

	// Ensure shared strings are preloaded
	if !f.fastSSTLoaded {
		if err := f.preloadSharedStrings(); err != nil {
			return nil, err
		}
	}

	// Get reader for sheet XML
	var reader io.Reader
	var closer io.Closer

	if data := f.readXML(name); len(data) > 0 {
		reader = bytes.NewReader(data)
	} else if path, ok := f.tempFiles.Load(name); ok {
		file, err := os.Open(path.(string))
		if err != nil {
			return nil, err
		}
		reader = file
		closer = file
	} else {
		return nil, ErrSheetNotExist{sheet}
	}

	return &FastRows{
		f:       f,
		reader:  bufio.NewReaderSize(reader, 256*1024), // 256KB buffer
		closer:  closer,
		cellBuf: make([]byte, 0, 256),
	}, nil
}

// Close releases resources held by the FastRows iterator.
func (fr *FastRows) Close() error {
	if fr.closer != nil {
		return fr.closer.Close()
	}
	return nil
}

// Next advances to the next row. Returns false when no more rows.
func (fr *FastRows) Next() bool {
	if fr.eof {
		return false
	}

	// Reset row buffer, keeping capacity
	if fr.numCols > 0 && cap(fr.rowBuf) >= fr.numCols {
		fr.rowBuf = fr.rowBuf[:0]
	} else if fr.numCols > 0 {
		fr.rowBuf = make([]string, 0, fr.numCols)
	} else {
		fr.rowBuf = fr.rowBuf[:0]
	}

	// Scan for next <row> element
	for {
		_, err := fr.reader.ReadSlice('<')
		if err != nil {
			fr.eof = true
			return false
		}

		// Peek to see what element this is
		peek, err := fr.reader.Peek(10)
		if err != nil && err != io.EOF {
			fr.eof = true
			return false
		}

		if len(peek) >= 3 && string(peek[:3]) == "row" {
			// Check it's actually <row and not <rows or similar
			if len(peek) >= 4 && (peek[3] == ' ' || peek[3] == '>' || peek[3] == '/') {
				// Found <row>, parse row number and cells
				fr.curRow++
				fr.parseRow()
				if fr.numCols == 0 && len(fr.rowBuf) > 0 {
					fr.numCols = len(fr.rowBuf)
				}
				return true
			}
		} else if len(peek) >= 10 && string(peek[:10]) == "/sheetData" {
			fr.eof = true
			return false
		}
	}
}

// Row returns the current row's cell values. The returned slice is reused
// between calls, so copy it if you need to retain the data.
func (fr *FastRows) Row() []string {
	return fr.rowBuf
}

// RowNum returns the current 1-based row number.
func (fr *FastRows) RowNum() int {
	return fr.curRow
}

// parseRow parses the current row element and extracts cell values.
func (fr *FastRows) parseRow() {
	// Skip to end of <row ...> opening tag
	fr.skipToChar('>')

	cellCol := 0
	for {
		// Read until next '<'
		_, err := fr.reader.ReadSlice('<')
		if err != nil {
			return
		}

		// Check what element
		peek, err := fr.reader.Peek(5)
		if err != nil && err != io.EOF {
			return
		}

		if len(peek) >= 4 && string(peek[:4]) == "/row" {
			// End of row
			fr.skipToChar('>')
			return
		}

		if len(peek) >= 1 && peek[0] == 'c' && (len(peek) < 2 || peek[1] == ' ' || peek[1] == '>') {
			// Found <c ...> cell element
			cellCol++
			cellRef, cellType, cellValue := fr.parseCell()

			// Calculate column from ref if present
			if len(cellRef) > 0 {
				cellCol = colRefToIndex(cellRef)
			}

			// Expand with blanks if needed
			for len(fr.rowBuf) < cellCol-1 {
				fr.rowBuf = append(fr.rowBuf, "")
			}

			// Resolve value based on type
			val := fr.resolveValue(cellType, cellValue)
			fr.rowBuf = append(fr.rowBuf, val)
		} else {
			// Skip other elements
			fr.skipElement()
		}
	}
}

// parseCell parses a <c> element and returns ref, type, and value.
func (fr *FastRows) parseCell() (ref, cellType, value string) {
	// Read the <c ...> tag attributes
	fr.cellBuf = fr.cellBuf[:0]
	for {
		b, err := fr.reader.ReadByte()
		if err != nil || b == '>' {
			break
		}
		if b == '/' {
			// Self-closing <c ... />
			fr.reader.ReadByte() // consume '>'
			return fr.parseCellAttrs(fr.cellBuf), "", ""
		}
		fr.cellBuf = append(fr.cellBuf, b)
	}

	ref, cellType = fr.parseCellAttrsWithType(fr.cellBuf)

	// Now read cell content looking for <v> or <is> (inline string)
	for {
		_, err := fr.reader.ReadSlice('<')
		if err != nil {
			return
		}

		peek, _ := fr.reader.Peek(3)
		if len(peek) >= 2 && peek[0] == '/' && peek[1] == 'c' {
			// End of cell
			fr.skipToChar('>')
			return
		}

		if len(peek) >= 1 && peek[0] == 'v' {
			// Found <v>
			fr.reader.Discard(1) // consume 'v'
			b, _ := fr.reader.ReadByte()
			if b == '>' {
				// Read value until </v>
				value = fr.readUntilEndTag("v")
			} else if b == '/' {
				// Empty <v/>
				fr.reader.ReadByte() // consume '>'
			}
		} else if len(peek) >= 2 && peek[0] == 'i' && peek[1] == 's' {
			// Found <is> inline string - need to extract <t>...</t> inside
			fr.reader.Discard(2) // consume 'is'
			fr.skipToChar('>')   // skip to end of <is> or <is ...>
			// Now find <t>
			for {
				_, err := fr.reader.ReadSlice('<')
				if err != nil {
					return
				}
				innerPeek, _ := fr.reader.Peek(3)
				if len(innerPeek) >= 2 && innerPeek[0] == '/' && innerPeek[1] == 'i' {
					// End of </is>
					fr.skipToChar('>')
					break
				}
				if len(innerPeek) >= 1 && innerPeek[0] == 't' {
					// Found <t>
					fr.reader.Discard(1) // consume 't'
					b, _ := fr.reader.ReadByte()
					if b == '>' {
						value = fr.readUntilEndTag("t")
					} else if b == ' ' {
						// <t xml:space="preserve">
						fr.skipToChar('>')
						value = fr.readUntilEndTag("t")
					} else if b == '/' {
						// Empty <t/>
						fr.reader.ReadByte() // consume '>'
					}
				} else {
					// Skip other elements inside <is>
					fr.skipElement()
				}
			}
		} else {
			// Skip other elements (like <f>)
			fr.skipElement()
		}
	}
}

// parseCellAttrs extracts the 'r' attribute from cell attributes.
func (fr *FastRows) parseCellAttrs(attrs []byte) string {
	// Look for r="..."
	idx := bytes.Index(attrs, []byte(`r="`))
	if idx < 0 {
		return ""
	}
	start := idx + 3
	end := bytes.IndexByte(attrs[start:], '"')
	if end < 0 {
		return ""
	}
	return string(attrs[start : start+end])
}

// parseCellAttrsWithType extracts 'r' and 't' attributes.
func (fr *FastRows) parseCellAttrsWithType(attrs []byte) (ref, cellType string) {
	// Look for r="..."
	if idx := bytes.Index(attrs, []byte(`r="`)); idx >= 0 {
		start := idx + 3
		if end := bytes.IndexByte(attrs[start:], '"'); end >= 0 {
			ref = string(attrs[start : start+end])
		}
	}
	// Look for t="..."
	if idx := bytes.Index(attrs, []byte(`t="`)); idx >= 0 {
		start := idx + 3
		if end := bytes.IndexByte(attrs[start:], '"'); end >= 0 {
			cellType = string(attrs[start : start+end])
		}
	}
	return
}

// resolveValue resolves the cell value based on type.
func (fr *FastRows) resolveValue(cellType, rawValue string) string {
	switch cellType {
	case "s": // shared string
		if idx, err := strconv.Atoi(rawValue); err == nil && idx >= 0 && idx < len(fr.f.fastSST) {
			return fr.f.fastSST[idx]
		}
		return rawValue
	case "b": // boolean
		if rawValue == "1" {
			return "TRUE"
		}
		return "FALSE"
	default:
		return rawValue
	}
}

// readUntilEndTag reads content until </tag>.
func (fr *FastRows) readUntilEndTag(tag string) string {
	fr.cellBuf = fr.cellBuf[:0]
	for {
		b, err := fr.reader.ReadByte()
		if err != nil {
			return string(fr.cellBuf)
		}
		if b == '<' {
			peek, _ := fr.reader.Peek(len(tag) + 1)
			if len(peek) >= len(tag)+1 && peek[0] == '/' && string(peek[1:len(tag)+1]) == tag {
				fr.reader.Discard(len(tag) + 1)
				fr.reader.ReadByte() // consume '>'
				return string(fr.cellBuf)
			}
			fr.cellBuf = append(fr.cellBuf, b)
		} else {
			fr.cellBuf = append(fr.cellBuf, b)
		}
	}
}

// skipToChar reads until the specified character is found.
func (fr *FastRows) skipToChar(c byte) {
	for {
		b, err := fr.reader.ReadByte()
		if err != nil || b == c {
			return
		}
	}
}

// skipElement skips the current element and its content.
// Called after we've read '<' and peeked the element name.
func (fr *FastRows) skipElement() {
	// First, skip to end of opening tag, checking for self-closing
	inAttr := false
	for {
		b, err := fr.reader.ReadByte()
		if err != nil {
			return
		}
		if b == '"' {
			inAttr = !inAttr
		} else if !inAttr {
			if b == '/' {
				// Check for self-closing tag />
				next, _ := fr.reader.Peek(1)
				if len(next) > 0 && next[0] == '>' {
					fr.reader.ReadByte() // consume '>'
					return               // Self-closing element, done
				}
			} else if b == '>' {
				// End of opening tag, now need to find matching close tag
				break
			}
		}
	}

	// Now skip content until matching close tag
	depth := 1
	for depth > 0 {
		// Find next '<'
		_, err := fr.reader.ReadSlice('<')
		if err != nil {
			return
		}

		// Check what kind of tag
		b, err := fr.reader.ReadByte()
		if err != nil {
			return
		}

		if b == '/' {
			// Closing tag
			depth--
			fr.skipToChar('>') // consume rest of closing tag
		} else if b == '!' || b == '?' {
			// Comment or processing instruction, skip to end
			fr.skipToChar('>')
		} else {
			// Opening tag - need to check if self-closing
			selfClosing := false
			inAttr := false
			for {
				c, err := fr.reader.ReadByte()
				if err != nil {
					return
				}
				if c == '"' {
					inAttr = !inAttr
				} else if !inAttr {
					if c == '/' {
						next, _ := fr.reader.Peek(1)
						if len(next) > 0 && next[0] == '>' {
							fr.reader.ReadByte() // consume '>'
							selfClosing = true
							break
						}
					} else if c == '>' {
						break
					}
				}
			}
			if !selfClosing {
				depth++
			}
		}
	}
}

// preloadSharedStrings parses xl/sharedStrings.xml once and stores all string
// values in fastSST as a flat []string slice. This is used in FastReadMode to
// eliminate per-cell ReadAt syscalls. The slice is indexed by the shared
// string index (the <v> content for type="s" cells).
func (f *File) preloadSharedStrings() error {
	if f.fastSSTLoaded {
		return nil
	}

	// Quick check: if there's no shared strings data, skip preloading
	if content := f.readXML(defaultXMLPathSharedStrings); len(content) == 0 {
		// Check if it's in temp files
		if _, ok := f.tempFiles.Load(defaultXMLPathSharedStrings); !ok {
			f.fastSSTLoaded = true
			return nil
		}
	}

	needClose, decoder, tempFile, err := f.xmlDecoder(defaultXMLPathSharedStrings)
	if err != nil {
		return err
	}
	if needClose {
		defer tempFile.Close()
	}

	// Pre-allocate based on typical shared string counts
	f.fastSST = make([]string, 0, 4096)

	// SAX-style parsing: track state to extract text content efficiently
	// without using DecodeElement which involves reflection overhead.
	var (
		inSI  bool            // inside <si> element
		inT   bool            // inside <t> element (text content)
		buf   strings.Builder // accumulate text for current <si>
		depth int             // track nesting depth within <si>
	)

	for {
		token, err := decoder.Token()
		if err != nil || token == nil {
			break
		}
		switch t := token.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "si":
				inSI = true
				depth = 1
				buf.Reset()
			case "t":
				if inSI {
					inT = true
				}
			default:
				if inSI {
					depth++
				}
			}
		case xml.EndElement:
			switch t.Name.Local {
			case "si":
				f.fastSST = append(f.fastSST, buf.String())
				inSI = false
				depth = 0
			case "t":
				inT = false
			default:
				if inSI {
					depth--
				}
			}
		case xml.CharData:
			if inT {
				buf.Write(t)
			}
		}
	}
	f.fastSSTLoaded = true
	return nil
}

// getFromStringItemFast returns the shared string value by index using the
// preloaded fastSST slice. Falls back to the slow path if not preloaded.
func (f *File) getFromStringItemFast(index int) string {
	if f.fastSSTLoaded {
		if index >= 0 && index < len(f.fastSST) {
			return f.fastSST[index]
		}
		return strconv.Itoa(index)
	}
	return f.getFromStringItem(index)
}

// getFromStringItem build shared string item offset list from system temporary
// file at one time, and return value by given to string index.
func (f *File) getFromStringItem(index int) string {
	// Fast path: use preloaded shared strings if available
	if f.fastSSTLoaded && len(f.fastSST) > 0 {
		if index >= 0 && index < len(f.fastSST) {
			return f.fastSST[index]
		}
		return strconv.Itoa(index)
	}
	if f.sharedStringTemp != nil {
		if len(f.sharedStringItem) <= index {
			return strconv.Itoa(index)
		}
		offsetRange := f.sharedStringItem[index]
		if len(offsetRange) != 2 || offsetRange[0] > offsetRange[1] {
			return strconv.Itoa(index)
		}
		buf := make([]byte, offsetRange[1]-offsetRange[0])
		if _, err := f.sharedStringTemp.ReadAt(buf, int64(offsetRange[0])); err != nil {
			return strconv.Itoa(index)
		}
		return string(buf)
	}
	needClose, decoder, tempFile, err := f.xmlDecoder(defaultXMLPathSharedStrings)
	if needClose && err == nil {
		defer func() {
			err = tempFile.Close()
		}()
	}
	f.sharedStringItem = [][]uint{}
	f.sharedStringTemp, _ = os.CreateTemp(f.options.TmpDir, "excelize-")
	f.tempFiles.Store(defaultTempFileSST, f.sharedStringTemp.Name())
	var (
		inElement string
		i, offset uint
	)
	for {
		token, _ := decoder.Token()
		if token == nil {
			break
		}
		switch xmlElement := token.(type) {
		case xml.StartElement:
			inElement = xmlElement.Name.Local
			if inElement == "si" {
				si := xlsxSI{}
				_ = decoder.DecodeElement(&si, &xmlElement)

				startIdx := offset
				n, _ := f.sharedStringTemp.WriteString(si.String())
				offset += uint(n)
				f.sharedStringItem = append(f.sharedStringItem, []uint{startIdx, offset})
				i++
			}
		}
	}
	return f.getFromStringItem(index)
}

// xmlDecoder creates XML decoder by given path in the zip from memory data
// or system temporary file.
func (f *File) xmlDecoder(name string) (bool, *xml.Decoder, *os.File, error) {
	var (
		content  []byte
		err      error
		tempFile *os.File
	)
	if content = f.readXML(name); len(content) > 0 {
		return false, f.xmlNewDecoder(bytes.NewReader(content)), tempFile, err
	}
	tempFile, err = f.readTemp(name)
	// Use a large buffered reader to minimize read syscalls. Without this,
	// the xml.Decoder uses a 4 KB internal buffer, generating thousands of
	// syscalls for large worksheets. A 256 KB buffer reduces that by ~60×.
	const readBufSize = 256 * 1024
	br := bufio.NewReaderSize(tempFile, readBufSize)
	return true, f.xmlNewDecoder(br), tempFile, err
}

// SetRowHeight provides a function to set the height of a single row. If the
// value of height is 0, will hide the specified row, if the value of height is
// -1, will unset the custom row height. For example, set the height of the
// first row in Sheet1:
//
//	err := f.SetRowHeight("Sheet1", 1, 50)
func (f *File) SetRowHeight(sheet string, row int, height float64) error {
	if row < 1 {
		return newInvalidRowNumberError(row)
	}
	if height > MaxRowHeight {
		return ErrMaxRowHeight
	}
	if height < -1 {
		return ErrParameterInvalid
	}
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}

	ws.prepareSheetXML(0, row)

	rowIdx := row - 1
	if height == -1 {
		ws.SheetData.Row[rowIdx].Ht = nil
		ws.SheetData.Row[rowIdx].CustomHeight = false
		return err
	}
	ws.SheetData.Row[rowIdx].Ht = float64Ptr(height)
	ws.SheetData.Row[rowIdx].CustomHeight = true
	return err
}

// getRowHeight provides a function to get row height in pixels by given sheet
// name and row number.
func (f *File) getRowHeight(sheet string, row int) int {
	ws, _ := f.workSheetReader(sheet)
	ws.mu.Lock()
	defer ws.mu.Unlock()
	height := -1.0
	for i := range ws.SheetData.Row {
		v := &ws.SheetData.Row[i]
		if v.R == row && v.Ht != nil {
			height = *v.Ht
			break
		}
	}
	if height != -1.0 {
		return int(convertRowHeightToPixels(height))
	}
	if ws.SheetFormatPr != nil && ws.SheetFormatPr.DefaultRowHeight > 0 {
		return int(convertRowHeightToPixels(ws.SheetFormatPr.DefaultRowHeight))
	}
	// Optimization for when the row heights haven't changed.
	return int(defaultRowHeightPixels)
}

// GetRowHeight provides a function to get row height by given worksheet name
// and row number. For example, get the height of the first row in Sheet1:
//
//	height, err := f.GetRowHeight("Sheet1", 1)
func (f *File) GetRowHeight(sheet string, row int) (float64, error) {
	if row < 1 {
		return defaultRowHeight, newInvalidRowNumberError(row)
	}
	ht := defaultRowHeight
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return ht, err
	}
	if ws.SheetFormatPr != nil && ws.SheetFormatPr.CustomHeight {
		ht = ws.SheetFormatPr.DefaultRowHeight
	}
	if row > len(ws.SheetData.Row) {
		return ht, nil // it will be better to use 0, but we take care with BC
	}
	for _, v := range ws.SheetData.Row {
		if v.R == row && v.Ht != nil {
			return *v.Ht, nil
		}
	}
	// Optimization for when the row heights haven't changed.
	return ht, nil
}

// sharedStringsReader provides a function to get the pointer to the structure
// after deserialization of xl/sharedStrings.xml.
func (f *File) sharedStringsReader() (*xlsxSST, error) {
	var err error
	f.mu.Lock()
	defer f.mu.Unlock()
	relPath := f.getWorkbookRelsPath()
	if f.SharedStrings == nil {
		var sharedStrings xlsxSST
		ss := f.readXML(defaultXMLPathSharedStrings)
		if err = f.xmlNewDecoder(bytes.NewReader(namespaceStrictToTransitional(ss))).
			Decode(&sharedStrings); err != nil && err != io.EOF {
			return f.SharedStrings, err
		}
		if sharedStrings.Count == 0 {
			sharedStrings.Count = len(sharedStrings.SI)
		}
		if sharedStrings.UniqueCount == 0 {
			sharedStrings.UniqueCount = sharedStrings.Count
		}
		f.SharedStrings = &sharedStrings
		for i := range sharedStrings.SI {
			if sharedStrings.SI[i].T != nil {
				f.sharedStringsMap[sharedStrings.SI[i].T.Val] = i
			}
		}
		if err = f.addContentTypePart(0, "sharedStrings"); err != nil {
			return f.SharedStrings, err
		}
		rels, err := f.relsReader(relPath)
		if err != nil {
			return f.SharedStrings, err
		}
		for _, rel := range rels.Relationships {
			if rel.Target == "/xl/sharedStrings.xml" {
				return f.SharedStrings, nil
			}
		}
		// Update workbook.xml.rels
		f.addRels(relPath, SourceRelationshipSharedStrings, "/xl/sharedStrings.xml", "")
	}

	return f.SharedStrings, nil
}

// SetRowVisible provides a function to set visible of a single row by given
// worksheet name and Excel row number. For example, hide row 2 in Sheet1:
//
//	err := f.SetRowVisible("Sheet1", 2, false)
func (f *File) SetRowVisible(sheet string, row int, visible bool) error {
	if row < 1 {
		return newInvalidRowNumberError(row)
	}

	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}
	ws.prepareSheetXML(0, row)
	ws.SheetData.Row[row-1].Hidden = !visible
	return nil
}

// GetRowVisible provides a function to get visible of a single row by given
// worksheet name and Excel row number. For example, get visible state of row
// 2 in Sheet1:
//
//	visible, err := f.GetRowVisible("Sheet1", 2)
func (f *File) GetRowVisible(sheet string, row int) (bool, error) {
	if row < 1 {
		return false, newInvalidRowNumberError(row)
	}

	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return false, err
	}
	if row > len(ws.SheetData.Row) {
		return false, nil
	}
	return !ws.SheetData.Row[row-1].Hidden, nil
}

// SetRowOutlineLevel provides a function to set outline level number of a
// single row by given worksheet name and row number. The range of 'level'
// parameter value from 1 to 7. For example, outline row 2 in Sheet1 to level 1:
//
//	err := f.SetRowOutlineLevel("Sheet1", 2, 1)
func (f *File) SetRowOutlineLevel(sheet string, row int, level uint8) error {
	if row < 1 {
		return newInvalidRowNumberError(row)
	}
	if level > 7 || level < 1 {
		return ErrOutlineLevel
	}
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}
	ws.prepareSheetXML(0, row)
	ws.SheetData.Row[row-1].OutlineLevel = level
	return nil
}

// GetRowOutlineLevel provides a function to get outline level number of a
// single row by given worksheet name and Excel row number. For example, get
// outline number of row 2 in Sheet1:
//
//	level, err := f.GetRowOutlineLevel("Sheet1", 2)
func (f *File) GetRowOutlineLevel(sheet string, row int) (uint8, error) {
	if row < 1 {
		return 0, newInvalidRowNumberError(row)
	}
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return 0, err
	}
	if row > len(ws.SheetData.Row) {
		return 0, nil
	}
	return ws.SheetData.Row[row-1].OutlineLevel, nil
}

// RemoveRow provides a function to remove single row by given worksheet name
// and Excel row number. For example, remove row 3 in Sheet1:
//
//	err := f.RemoveRow("Sheet1", 3)
//
// Use this method with caution, which will affect changes in references such
// as formulas, charts, and so on. If there is any referenced value of the
// worksheet, it will cause a file error when you open it. The excelize only
// partially updates these references currently.
func (f *File) RemoveRow(sheet string, row int) error {
	if row < 1 {
		return newInvalidRowNumberError(row)
	}

	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}
	ws.formulaSI.Clear()
	if row > len(ws.SheetData.Row) {
		return f.adjustHelper(sheet, rows, row, -1)
	}
	for rowIdx := range ws.SheetData.Row {
		v := &ws.SheetData.Row[rowIdx]
		if v.R == row {
			for _, c := range v.C {
				if err := f.removeFormula(&c, ws, sheet); err != nil {
					return err
				}
			}
		}
	}
	keep := 0
	for rowIdx := range ws.SheetData.Row {
		v := &ws.SheetData.Row[rowIdx]
		if v.R != row {
			ws.SheetData.Row[keep] = *v
			keep++
		}
	}
	ws.SheetData.Row = ws.SheetData.Row[:keep]
	return f.adjustHelper(sheet, rows, row, -1)
}

// InsertRows provides a function to insert new rows after the given Excel row
// number starting from 1 and number of rows. For example, create two rows
// before row 3 in Sheet1:
//
//	err := f.InsertRows("Sheet1", 3, 2)
//
// Use this method with caution, which will affect changes in references such
// as formulas, charts, and so on. If there is any referenced value of the
// worksheet, it will cause a file error when you open it. The excelize only
// partially updates these references currently.
func (f *File) InsertRows(sheet string, row, n int) error {
	if row < 1 {
		return newInvalidRowNumberError(row)
	}
	if row >= TotalRows || n >= TotalRows {
		return ErrMaxRows
	}
	if n < 1 {
		return ErrParameterInvalid
	}
	return f.adjustHelper(sheet, rows, row, n)
}

// DuplicateRow inserts a copy of specified row (by its Excel row number) below
//
//	err := f.DuplicateRow("Sheet1", 2)
//
// Use this method with caution, which will affect changes in references such
// as formulas, charts, and so on. If there is any referenced value of the
// worksheet, it will cause a file error when you open it. The excelize only
// partially updates these references currently.
func (f *File) DuplicateRow(sheet string, row int) error {
	return f.DuplicateRowTo(sheet, row, row+1)
}

// DuplicateRowTo inserts a copy of specified row by it Excel number
// to specified row position moving down exists rows after target position
//
//	err := f.DuplicateRowTo("Sheet1", 2, 7)
//
// Use this method with caution, which will affect changes in references such
// as formulas, charts, and so on. If there is any referenced value of the
// worksheet, it will cause a file error when you open it. The excelize only
// partially updates these references currently.
func (f *File) DuplicateRowTo(sheet string, row, row2 int) error {
	if row < 1 {
		return newInvalidRowNumberError(row)
	}

	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}

	if row2 < 1 || row == row2 {
		return err
	}

	var ok bool
	var rowCopy xlsxRow

	for i, r := range ws.SheetData.Row {
		if r.R == row {
			err = deepcopy.Copy(&rowCopy, ws.SheetData.Row[i])
			ok = true
			break
		}
	}

	if err := f.adjustHelper(sheet, rows, row2, 1); err != nil {
		return err
	}

	if !ok {
		return err
	}

	idx2 := -1
	for i, r := range ws.SheetData.Row {
		if r.R == row2 {
			idx2 = i
			break
		}
	}
	rowCopy.C = append(make([]xlsxC, 0, len(rowCopy.C)), rowCopy.C...)
	rowCopy.adjustSingleRowDimensions(row2 - row)
	_ = f.adjustSingleRowFormulas(sheet, sheet, &rowCopy, row, row2-row, true)

	if idx2 != -1 {
		ws.SheetData.Row[idx2] = rowCopy
	} else {
		ws.SheetData.Row = append(ws.SheetData.Row, rowCopy)
	}
	for _, fn := range duplicateHelperFunc {
		if err := fn(f, ws, sheet, row, row2); err != nil {
			return err
		}
	}
	return err
}

// duplicateSQRefHelper provides a function to adjust conditional formatting and
// data validations cell reference when duplicate rows.
func duplicateSQRefHelper(row, row2 int, ref string) (string, error) {
	if !strings.Contains(ref, ":") {
		ref += ":" + ref
	}
	abs := strings.Contains(ref, "$")
	coordinates, err := rangeRefToCoordinates(ref)
	if err != nil {
		return "", err
	}
	x1, y1, x2, y2 := coordinates[0], coordinates[1], coordinates[2], coordinates[3]
	if y1 == y2 && y1 == row {
		if ref, err = coordinatesToRangeRef([]int{x1, row2, x2, row2}, abs); err != nil {
			return "", err
		}
		return ref, err
	}
	return "", err
}

// duplicateConditionalFormat create conditional formatting for the destination
// row if there are conditional formats in the copied row.
func (f *File) duplicateConditionalFormat(ws *xlsxWorksheet, sheet string, row, row2 int) error {
	var cfs []*xlsxConditionalFormatting
	for _, cf := range ws.ConditionalFormatting {
		if cf != nil {
			var SQRef []string
			for _, ref := range strings.Split(cf.SQRef, " ") {
				coordinates, err := duplicateSQRefHelper(row, row2, ref)
				if err != nil {
					return err
				}
				if coordinates != "" {
					SQRef = append(SQRef, coordinates)
				}
			}
			if len(SQRef) > 0 {
				var cfCopy xlsxConditionalFormatting
				_ = deepcopy.Copy(&cfCopy, *cf)
				cfCopy.SQRef = strings.Join(SQRef, " ")
				cfs = append(cfs, &cfCopy)
			}
		}
	}
	ws.ConditionalFormatting = append(ws.ConditionalFormatting, cfs...)
	return nil
}

// duplicateDataValidations create data validations for the destination row if
// there are data validation rules in the copied row.
func (f *File) duplicateDataValidations(ws *xlsxWorksheet, sheet string, row, row2 int) error {
	if ws.DataValidations == nil {
		return nil
	}
	var dvs []*xlsxDataValidation
	for _, dv := range ws.DataValidations.DataValidation {
		if dv != nil {
			var SQRef []string
			for _, ref := range strings.Split(dv.Sqref, " ") {
				coordinates, err := duplicateSQRefHelper(row, row2, ref)
				if err != nil {
					return err
				}
				if coordinates != "" {
					SQRef = append(SQRef, coordinates)
				}
			}
			if len(SQRef) > 0 {
				var dvCopy xlsxDataValidation
				_ = deepcopy.Copy(&dvCopy, *dv)
				dvCopy.Sqref = strings.Join(SQRef, " ")
				dvs = append(dvs, &dvCopy)
			}
		}
	}
	ws.DataValidations.DataValidation = append(ws.DataValidations.DataValidation, dvs...)
	return nil
}

// duplicateMergeCells merge cells in the destination row if there are single
// row merged cells in the copied row.
func (f *File) duplicateMergeCells(ws *xlsxWorksheet, sheet string, row, row2 int) error {
	if ws.MergeCells == nil {
		return nil
	}
	if row > row2 {
		row++
	}
	for _, rng := range ws.MergeCells.Cells {
		coordinates, err := rangeRefToCoordinates(rng.Ref)
		if err != nil {
			return err
		}
		if coordinates[1] < row2 && row2 < coordinates[3] {
			return nil
		}
	}
	for i := 0; i < len(ws.MergeCells.Cells); i++ {
		mergedCells := ws.MergeCells.Cells[i]
		coordinates, _ := rangeRefToCoordinates(mergedCells.Ref)
		x1, y1, x2, y2 := coordinates[0], coordinates[1], coordinates[2], coordinates[3]
		if y1 == y2 && y1 == row {
			from, _ := CoordinatesToCellName(x1, row2)
			to, _ := CoordinatesToCellName(x2, row2)
			if err := f.MergeCell(sheet, from, to); err != nil {
				return err
			}
		}
	}
	return nil
}

// checkRow provides a function to check and fill each column element for all
// rows and make that is continuous in a worksheet of XML. For example:
//
//	<row r="15">
//	    <c r="A15" s="2" />
//	    <c r="B15" s="2" />
//	    <c r="F15" s="1" />
//	    <c r="G15" s="1" />
//	</row>
//
// in this case, we should to change it to
//
//	<row r="15">
//	    <c r="A15" s="2" />
//	    <c r="B15" s="2" />
//	    <c r="C15" s="2" />
//	    <c r="D15" s="2" />
//	    <c r="E15" s="2" />
//	    <c r="F15" s="1" />
//	    <c r="G15" s="1" />
//	</row>
//
// Notice: this method could be very slow for large spreadsheets (more than
// 3000 rows one sheet).
func (ws *xlsxWorksheet) checkRow() error {
	for rowIdx := range ws.SheetData.Row {
		rowData := &ws.SheetData.Row[rowIdx]

		colCount := len(rowData.C)
		if colCount == 0 {
			continue
		}
		// check and fill the cell without r attribute in a row element
		rCount := 0
		for idx, cell := range rowData.C {
			rCount++
			if cell.R != "" {
				lastR, _, err := CellNameToCoordinates(cell.R)
				if err != nil {
					return err
				}
				if lastR > rCount {
					rCount = lastR
				}
				continue
			}
			rowData.C[idx].R, _ = CoordinatesToCellName(rCount, rowIdx+1)
		}
		lastCol, _, err := CellNameToCoordinates(rowData.C[colCount-1].R)
		if err != nil {
			return err
		}

		if colCount < lastCol {
			sourceList := rowData.C
			targetList := make([]xlsxC, 0, lastCol)

			rowData.C = ws.SheetData.Row[rowIdx].C[:0]

			for colIdx := 0; colIdx < lastCol; colIdx++ {
				cellName, err := CoordinatesToCellName(colIdx+1, rowIdx+1)
				if err != nil {
					return err
				}
				targetList = append(targetList, xlsxC{R: cellName})
			}

			rowData.C = targetList

			for colIdx := range sourceList {
				colData := &sourceList[colIdx]
				colNum, _, err := CellNameToCoordinates(colData.R)
				if err != nil {
					return err
				}
				ws.SheetData.Row[rowIdx].C[colNum-1] = *colData
			}
		}
	}
	return nil
}

// hasAttr determine if row non-default attributes.
func (r *xlsxRow) hasAttr() bool {
	return r.Spans != "" || r.S != 0 || r.CustomFormat || r.Ht != nil ||
		r.Hidden || r.CustomHeight || r.OutlineLevel != 0 || r.Collapsed ||
		r.ThickTop || r.ThickBot || r.Ph
}

// SetRowStyle provides a function to set the style of rows by given worksheet
// name, row range, and style ID. Note that this will overwrite the existing
// styles for the rows, it won't append or merge style with existing styles.
//
// For example set style of row 1 on Sheet1:
//
//	err := f.SetRowStyle("Sheet1", 1, 1, styleID)
//
// Set style of rows 1 to 10 on Sheet1:
//
//	err := f.SetRowStyle("Sheet1", 1, 10, styleID)
func (f *File) SetRowStyle(sheet string, start, end, styleID int) error {
	if end < start {
		start, end = end, start
	}
	if start < 1 {
		return newInvalidRowNumberError(start)
	}
	if end > TotalRows {
		return ErrMaxRows
	}
	s, err := f.stylesReader()
	if err != nil {
		return err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if styleID < 0 || s.CellXfs == nil || len(s.CellXfs.Xf) <= styleID {
		return newInvalidStyleID(styleID)
	}
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		return err
	}
	ws.prepareSheetXML(0, end)
	for row := start - 1; row < end; row++ {
		ws.SheetData.Row[row].S = styleID
		ws.SheetData.Row[row].CustomFormat = true
		for i := range ws.SheetData.Row[row].C {
			if _, rowNum, err := CellNameToCoordinates(ws.SheetData.Row[row].C[i].R); err == nil && rowNum-1 == row {
				ws.SheetData.Row[row].C[i].S = styleID
			}
		}
	}
	return nil
}

// convertRowHeightToPixels provides a function to convert the height of a
// cell from user's units to pixels. If the height hasn't been set by the user
// we use the default value. If the row is hidden it has a value of zero.
func convertRowHeightToPixels(height float64) float64 {
	if height == 0 {
		return 0
	}
	return math.Ceil(4.0 / 3.4 * height)
}
