// Copyright 2016 - 2024 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.18 or later.

package excelize

import "encoding/xml"

// xlsxMetadata directly maps the metadata element. A cell in a spreadsheet
// application can have metadata associated with it. Metadata is just a set of
// additional properties about the particular cell, and this metadata is stored
// in the metadata xml part. There are two types of metadata: cell metadata and
// value metadata. Cell metadata contains information about the cell itself,
// and this metadata can be carried along with the cell as it moves
// (insert, shift, copy/paste, merge, unmerge, etc). Value metadata is
// information about the value of a particular cell. Value metadata properties
// can be propagated along with the value as it is referenced in formulas.
type xlsxMetadata struct {
	XMLName         xml.Name             `xml:"metadata"`
	MetadataTypes   *xlsxInnerXML        `xml:"metadataTypes"`
	MetadataStrings *xlsxInnerXML        `xml:"metadataStrings"`
	MdxMetadata     *xlsxInnerXML        `xml:"mdxMetadata"`
	FutureMetadata  []xlsxFutureMetadata `xml:"futureMetadata"`
	CellMetadata    *xlsxMetadataBlocks  `xml:"cellMetadata"`
	ValueMetadata   *xlsxMetadataBlocks  `xml:"valueMetadata"`
	ExtLst          *xlsxInnerXML        `xml:"extLst"`
}

// xlsxFutureMetadata directly maps the futureMetadata element. This element
// represents future metadata information.
type xlsxFutureMetadata struct {
	Bk     []xlsxFutureMetadataBlock `xml:"bk"`
	ExtLst *xlsxInnerXML             `xml:"extLst"`
}

// xlsxFutureMetadataBlock directly maps the kb element. This element represents
// a block of future metadata information. This is a location for storing
// feature extension information.
type xlsxFutureMetadataBlock struct {
	ExtLst *xlsxInnerXML `xml:"extLst"`
}

// xlsxMetadataBlocks directly maps the metadata element. This element
// represents cell metadata information. Cell metadata is information metadata
// about a specific cell, and it stays tied to that cell position.
type xlsxMetadataBlocks struct {
	Count int                 `xml:"count,attr,omitempty"`
	Bk    []xlsxMetadataBlock `xml:"bk"`
}

// xlsxMetadataBlock directly maps the bk element. This element represents a
// block of metadata records.
type xlsxMetadataBlock struct {
	Rc []xlsxMetadataRecord `xml:"rc"`
}

// xlsxMetadataRecord directly maps the rc element. This element represents a
// reference to a specific metadata record.
type xlsxMetadataRecord struct {
	T int `xml:"t,attr"`
	V int `xml:"v,attr"`
}

// xlsxRichValueArrayData directly maps the arrayData element that specifies rich value
// arrays.
type XlsxRichValueArrayData struct {
	XMLName xml.Name            `xml:"arrayData"`
	Xmlns   string              `xml:"xmlns,attr"`
	Count   string              `xml:"count,attr"`
	A       XlsxRichValuesArray `xml:"a"`
}

// xlsxRichValuesArray directly maps the a element that specifies rich values Array
// information for an array data
type XlsxRichValuesArray struct {
	R string               `xml:"r,attr"`
	C string               `xml:"c,attr"`
	V []XlsxRichArrayValue `xml:"v"`
}

// XlsxRichArrayValue directly maps the v element that specifies rich array value
// information for a values array
type XlsxRichArrayValue struct {
	Text string `xml:",chardata"`
	T    string `xml:"t,attr"`
}

// xlsxRichValueData directly maps the rvData element that specifies rich value
// data.
type xlsxRichValueData struct {
	XMLName xml.Name        `xml:"rvData"`
	Count   int             `xml:"count,attr,omitempty"`
	Rv      []xlsxRichValue `xml:"rv"`
	ExtLst  *xlsxInnerXML   `xml:"extLst"`
}

// xlsxRichValue directly maps the rv element that specifies rich value data
// information for a single rich value
type xlsxRichValue struct {
	S  int           `xml:"s,attr"`
	V  []string      `xml:"v"`
	Fb *xlsxInnerXML `xml:"fb"`
}

// xlsxRichValueRels directly maps the richValueRels element. This element that
// specifies a list of rich value relationships.
type xlsxRichValueRels struct {
	XMLName xml.Name                       `xml:"richValueRels"`
	Rels    []xlsxRichValueRelRelationship `xml:"rel"`
	ExtLst  *xlsxInnerXML                  `xml:"extLst"`
}

// xlsxRichValueRelRelationship directly maps the rel element. This element
// specifies a relationship for a rich value property.
type xlsxRichValueRelRelationship struct {
	ID string `xml:"id,attr"`
}

// XlsxRichValueStructures directly maps the rvStructures element that specifies rich value structure
// data.
type XlsxRichValueStructures struct {
	XMLName xml.Name                 `xml:"rvStructures"`
	Text    string                   `xml:",chardata"`
	Xmlns   string                   `xml:"xmlns,attr"`
	Count   string                   `xml:"count,attr"`
	S       []XlsxRichValueStructure `xml:"s"`
}

// XlsxRichValueStructure directly maps the s element that specifies rich value structure data
// information for a single rich value structure
type XlsxRichValueStructure struct {
	Text string                      `xml:",chardata"`
	T    string                      `xml:"t,attr"`
	K    []XlsxRichValueStructureKey `xml:"k"`
}

// XlsxRichValueStructureKey directly maps the k element that specifies rich value structure key data
// information for a structure
type XlsxRichValueStructureKey struct {
	Text string `xml:",chardata"`
	N    string `xml:"n,attr"`
	T    string `xml:"t,attr"`
}

// XlsxRichDataSupportingPropertyBags directly maps the supportingPropertyBags element that specifies supporting property bag data.
type XlsxRichDataSupportingPropertyBags struct {
	XMLName xml.Name            `xml:"supportingPropertyBags"`
	Text    string              `xml:",chardata"`
	Xmlns   string              `xml:"xmlns,attr"`
	SpbData XlsxRichDataSpbData `xml:"spbData"`
}

// XlsxRichDataSpbData directly maps the spbData element that specifies supporting property bag data.
type XlsxRichDataSpbData struct {
	Text  string            `xml:",chardata"`
	Count string            `xml:"count,attr"`
	Spb   []XlsxRichDataSpb `xml:"spb"`
}

// XlsxRichDataSpb directly maps the spb element that specifies data for a single supporting property bag.
type XlsxRichDataSpb struct {
	Text string   `xml:",chardata"`
	S    string   `xml:"s,attr"`
	V    []string `xml:"v"`
}

// XlsxRichDataSpbStructures directly maps the spbStructures element that specifies supporting property bag structure.
type XlsxRichDataSpbStructures struct {
	XMLName xml.Name                   `xml:"spbStructures"`
	Text    string                     `xml:",chardata"`
	Xmlns   string                     `xml:"xmlns,attr"`
	Count   string                     `xml:"count,attr"`
	S       []XlsxRichDataSpbStructure `xml:"s"`
}

// XlsxRichDataSpbStructure directly maps the s element that specifies spb structure information for a single spb structure
type XlsxRichDataSpbStructure struct {
	Text string                        `xml:",chardata"`
	K    []XlsxRichDataSpbStructureKey `xml:"k"`
}

// XlsxRichDataSpbStructureKey directly maps the k element that specifies spb structure key data and attributes information for a single spb structure
type XlsxRichDataSpbStructureKey struct {
	Text string `xml:",chardata"`
	N    string `xml:"n,attr"`
	T    string `xml:"t,attr"`
}

// xlsxWebImagesSupportingRichData directly maps the webImagesSrd element. This
// element specifies a list of sets of properties associated with web image rich
// values.
type xlsxWebImagesSupportingRichData struct {
	XMLName     xml.Name                         `xml:"webImagesSrd"`
	WebImageSrd []xlsxWebImageSupportingRichData `xml:"webImageSrd"`
	ExtLst      *xlsxInnerXML                    `xml:"extLst"`
}

// xlsxWebImageSupportingRichData directly maps the webImageSrd element. This
// element specifies a set of properties for a web image rich value.
type xlsxWebImageSupportingRichData struct {
	Address           xlsxExternalReference `xml:"address"`
	MoreImagesAddress xlsxExternalReference `xml:"moreImagesAddress"`
	Blip              xlsxExternalReference `xml:"blip"`
}
